export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";

export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";

export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const DETAIL_PRODUCTS_SUCCESS = "DETAIL_PRODUCTS_SUCCESS";

export const DETAIL_PRODUCTS_FAILURE = "DETAIL_PRODUCTS_FAILURE";

export const DELETE_PRODUCTS = "DELETE_PRODUCTS";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
